version: "3"

services:
  database:
    build:
      context: .
      dockerfile: CQSGateway.Database/Dockerfile
    image: cqsg/database
    container_name: cqsg-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=dev
    ports:
      - "27017:27017"